export const APPEARANCE = {
  variables: {
    fontFamily: "var(--font-ui)",
    fontFamilyButtons: "var(--font-ui)",
    colorPrimary: "#14150f",
    colorBackground: "transparent",
    colorText: "#14150f",
    colorTextSecondary: "#3a3a32",
    colorInputBackground: "#ffffff",
    colorInputText: "#14150f",
    colorNeutral: "#14150f",
    borderRadius: "6px",
    fontSize: "14px",
    spacingUnit: "0.875rem",
  },
  elements: {
    rootBox: { width: "100%" },
    cardBox: {
      width: "100%",
      boxShadow: "none",
      border: "none",
      overflow: "visible",
    },
    card: {
      background: "transparent",
      border: "none",
      boxShadow: "none",
      padding: 0,
      width: "100%",
    },
    header: { display: "none" },
    headerTitle: { display: "none" },
    headerSubtitle: { display: "none" },
    footer: { display: "none" },
    main: { gap: "16px", overflow: "visible" },
    form: { gap: "14px" },
    formField: { gap: "6px" },
    formFieldLabel: {
      color: "#14150f",
      fontSize: "13px",
      fontWeight: 500,
      letterSpacing: "-0.005em",
    },
    formFieldInput: {
      backgroundColor: "#ffffff",
      border: "1px solid #d8d3c4",
      borderRadius: "6px",
      boxSizing: "border-box",
      boxShadow: "none",
      color: "#14150f",
      fontSize: "14px",
      height: "44px",
      lineHeight: "20px",
      minHeight: "44px",
      padding: "11px 12px",
      transition: "border-color 120ms ease",
    },
    formFieldInput__focus: { borderColor: "#14150f", boxShadow: "none" },
    formButtonPrimary: {
      backgroundColor: "#14150f",
      backgroundImage: "none",
      border: "1px solid #14150f",
      borderRadius: "6px",
      boxSizing: "border-box",
      boxShadow: "none",
      color: "#fafaf7",
      display: "flex",
      fontSize: "14px",
      fontWeight: 500,
      height: "44px",
      justifyContent: "center",
      letterSpacing: "-0.005em",
      lineHeight: "20px",
      minHeight: "44px",
      overflow: "visible",
      padding: "11px 14px",
      textTransform: "none",
      transition: "background 120ms ease, opacity 120ms ease",
    },
    formButtonPrimary__hover: {
      backgroundColor: "#24261d",
    },
    socialButtons: { gap: "8px" },
    socialButtonsBlockButton: {
      backgroundColor: "#ffffff",
      border: "1px solid #d8d3c4",
      borderRadius: "6px",
      boxSizing: "border-box",
      boxShadow: "none",
      color: "#14150f",
      display: "flex",
      fontSize: "14px",
      fontWeight: 500,
      height: "44px",
      lineHeight: "20px",
      minHeight: "44px",
      overflow: "visible",
      padding: "11px 14px",
      textTransform: "none",
      transition: "background 120ms ease, border-color 120ms ease",
    },
    socialButtonsBlockButton__hover: {
      backgroundColor: "#fafaf7",
      borderColor: "#14150f",
    },
    socialButtonsBlockButtonText: {
      color: "#14150f",
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "20px",
      overflow: "visible",
    },
    socialButtonsProviderIcon: { flexShrink: 0 },
    dividerLine: { backgroundColor: "#e7e3d6" },
    dividerText: {
      color: "#6e6c64",
      fontSize: "11px",
      fontWeight: 500,
      letterSpacing: "0.08em",
      textTransform: "uppercase",
    },
    formFieldErrorText: { color: "#a8362a", fontSize: "12px" },
    identityPreview: {
      backgroundColor: "#ffffff",
      border: "1px solid #e7e3d6",
      borderRadius: "6px",
      boxShadow: "none",
    },
    identityPreviewText: { color: "#14150f", fontSize: "14px" },
    identityPreviewEditButton: { color: "#3a3a32" },
  },
};
